# NumPy 

In [9]:
import numpy as np

In [10]:
my_list = [1,2,3]

In [18]:
np.array(my_list)

array([1, 2, 3])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.63357496, 0.4298623 , 0.87782542, 0.76685744, 0.99026701])

In [25]:
np.random.rand(5,5)

array([[0.47712501, 0.12549663, 0.27172303, 0.54718913, 0.63962515],
       [0.60104326, 0.64091465, 0.00319535, 0.30551779, 0.44735834],
       [0.56750783, 0.43355644, 0.78668   , 0.99025481, 0.92481917],
       [0.10810192, 0.34564399, 0.391164  , 0.13881443, 0.3641335 ],
       [0.17900245, 0.69160566, 0.33329603, 0.60099126, 0.30378781]])

In [31]:
np.random.randint(1,100,(10,10))

array([[ 6, 28, 42, 92, 20, 49, 78, 78, 89, 66],
       [ 4,  9, 53, 76, 40, 99, 55, 96, 76, 57],
       [82, 89, 35, 17, 71, 60, 54, 42, 10, 45],
       [ 1, 23, 45, 18, 65, 45, 37, 83,  7, 21],
       [46, 99, 87, 26, 76, 25, 13, 64, 68, 43],
       [29, 61, 70, 81, 65, 15, 59, 58, 56, 99],
       [13, 53, 10, 14, 27, 28,  6, 86, 52, 10],
       [55, 97, 49, 61, 99, 31, 10, 86, 50, 70],
       [28, 23, 98, 73,  8, 29, 37, 61, 48, 91],
       [14, 86, 21, 98, 87, 34, 80, 77, 35, 45]])

In [38]:
arr = np.random.randint(1,10,(5,5))
print(arr)
arr[0][:] = 5
print(arr)

[[1 4 6 9 3]
 [9 4 7 4 9]
 [1 8 4 8 1]
 [1 5 2 9 3]
 [6 6 3 7 3]]
[[5 5 5 5 5]
 [9 4 7 4 9]
 [1 8 4 8 1]
 [1 5 2 9 3]
 [6 6 3 7 3]]


In [39]:
arr_2d = np.array([[1,4,7],[2,5,8],[3,6,9]])
arr_2d

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [56]:
arr_2d[1:3,:]

array([[2, 5, 8],
       [3, 6, 9]])

In [50]:
arr_1d = np.array([3,5,13,8,3,7])
arr_1d

array([ 3,  5, 13,  8,  3,  7])

In [51]:
arr_1d[arr_1d > 5]

array([13,  8,  7])

In [58]:
scalar_arr = np.arange(0,12)
scalar_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
scalar_arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])

In [61]:
scalar_arr * scalar_arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [64]:
scalar_arr / scalar_arr

C:\Users\Toshiba\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [67]:
np.exp(scalar_arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [68]:
np.sin(scalar_arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021])

In [69]:
np.exp(scalar_arr) == 1

array([ True, False, False, False, False, False, False, False, False,
       False, False, False])

# Pandas

In [70]:
import pandas as pd

In [72]:
labels = ["a","b","c"]
my_data = [10,20,30]
arr = np.array(my_data)
d = {"a":10, "b":20, "c":30}

In [78]:
pd.Series(data= my_data, index= labels)

a    10
b    20
c    30
dtype: int64

In [77]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [79]:
pd.Series(data= labels, index= arr)

10    a
20    b
30    c
dtype: object

In [80]:
pd.Series(data= arr, index= labels)

a    10
b    20
c    30
dtype: int32

In [82]:
ser1 = pd.Series(np.arange(1,5),["USA","Germany","USSR","Japan"])
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int32

In [89]:
ser2 = pd.Series([1,2,5,4],["USA","Germany","Italy","Japan"])
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [90]:
ser1["USA"]

1

In [96]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [100]:
np.random.seed(101)

In [101]:
df = pd.DataFrame(np.random.randn(5,4),["A","B","C","D","E"],["W","X","Y","Z"])
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [105]:
df["W"]

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [108]:
df[["W","Z"]]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [110]:
df["new"] = df["W"] + df["Z"]
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [118]:
df = df.drop("new",axis=1)

In [120]:
df.drop("E", axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [121]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [122]:
df.loc["A"]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [123]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [127]:
df.loc["B"]["W"]

0.6511179479432686

In [128]:
df.loc["B","W"]

0.6511179479432686

In [129]:
df.loc[["A","B"],["W","Y"]]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [131]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [132]:
df[df > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [137]:
df[df["W"] > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [141]:
df[df["W"] > 0]["W"]

A    2.706850
B    0.651118
D    0.188695
E    0.190794
Name: W, dtype: float64

In [150]:
df[(df["W"] > 0) & (df["Y"] > 1)] # use bitwise &(and) |(or)

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [151]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [154]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [155]:
newind = "CA NY WY OR CO".split()
df["States"] = newind

In [156]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [158]:
df.set_index("States")

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [159]:
outside = ["G1","G1","G1","G2","G2","G2"]
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [160]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [165]:
df = pd.DataFrame(np.random.randn(6,2),hier_index,["A","B"])
df

A         B
G1 1 -0.925874  1.862864
   2 -1.133817  0.610478
   3  0.386030  2.084019
G2 1 -0.376519  0.230336
   2  0.681209  1.035125
   3 -0.031160  1.939932

In [169]:
df.loc["G1"]

A         B
1 -0.925874  1.862864
2 -1.133817  0.610478
3  0.386030  2.084019

In [170]:
df.index.names = ["Groups","Num"]
df

A         B
Groups Num                    
G1     1   -0.925874  1.862864
       2   -1.133817  0.610478
       3    0.386030  2.084019
G2     1   -0.376519  0.230336
       2    0.681209  1.035125
       3   -0.031160  1.939932

In [171]:
df.loc["G2"].loc[2]["A"]

0.6812092925867574

In [172]:
df.xs(1,level="Num")

A         B
Groups                    
G1     -0.925874  1.862864
G2     -0.376519  0.230336

In [191]:
d = {"A":[1,2,np.nan], "B":[5,np.nan,np.nan], "C":[6,7,8]}
df = pd.DataFrame(d)
df

A    B  C
0  1.0  5.0  6
1  2.0  NaN  7
2  NaN  NaN  8

In [192]:
df.dropna(axis=1)

C
0  6
1  7
2  8

In [193]:
df.dropna(axis=0)

A    B  C
0  1.0  5.0  6

In [194]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  6
1  2.0  NaN  7

In [195]:
df.fillna(value="VALUE")

A      B  C
0      1      5  6
1      2  VALUE  7
2  VALUE  VALUE  8

In [198]:
df["A"] = df["A"].fillna(value=df["C"].max())

In [199]:
df

A    B  C
0  1.0  5.0  6
1  2.0  NaN  7
2  8.0  NaN  8

In [200]:
data = { "Location": ["IST","IST","ANK","IZM","ANT","ANT"], 
         "People": ["AYŞE", "TUFAN", "AHMET", "BATUHAN", "MERVE", "TUĞÇE"],
         "Salary": [200,300,400,200,500,400]
       }
df = pd.DataFrame(data)
by_location = df.groupby("Location")
by_location.sum()

Salary
Location        
ANK          400
ANT          900
IST          500
IZM          200

In [2]:
import pandas as pd
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [3]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [4]:
pd.concat([df1,df2])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [5]:
pd.concat([df1,df2],axis=1)

A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7

In [6]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [7]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [8]:
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [9]:
pd.merge(left,right,how='inner',on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [10]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [11]:
pd.merge(left, right, on=['key1', 'key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [12]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

In [13]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [14]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [15]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [16]:
left

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [17]:
right

C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [18]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [19]:
left.join(right, how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [20]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [21]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [22]:
df['col2'].nunique()

3

In [23]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [25]:
newdf = df[(df['col1']>2) & (df['col2']==444)]

In [26]:
newdf

col1  col2 col3
3     4   444  xyz

In [27]:
def times2(x):
    return x*2

In [28]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [29]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [30]:
df['col1'].sum()

10

In [31]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [32]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [33]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [34]:
df.sort_values(by='col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [35]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [36]:
df.dropna()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [37]:
import numpy as np
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [38]:
df.fillna('FILL')

col1  col2 col3
0     1  FILL  abc
1     2   555  def
2     3   666  ghi
3  FILL   444  xyz

In [39]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [40]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [41]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

# Data Reading and Writing

In [42]:
import numpy as np
import pandas as pd

In [43]:
pwd

'C:\\Users\\Toshiba\\Desktop\\DataScience101'

In [47]:
df = pd.read_csv('exampleIn')
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [45]:
df.to_csv('exampleOut',index=False)

In [49]:
pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [50]:
df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

### Note! reading from HTML requires additional packages

#### conda install lxml
#### conda install html5lib
#### conda install BeautifulSoup4